export const colorMap = {
  0: "#000000",
  1: "#090974",
  2: "#135f35",
  3: "#27eef0",
  4: "#a81618",
  5: "#d047e8",
  6: "#c56e1b",
  7: "#ffffff",
  8: "#827f7f",
  9: "#0202ef",
  A: "#17f527",
  B: "#d7f6f7",
  C: "#d4514a",
  D: "#f1a8ee",
  E: "#eff05f",
  F: "#f8fbf9",
};

export const commandDescriptionMap = {
  cd: 'Changes the directory. Usage: "cd [directory]" to navigate to a specific directory, or "cd .." to move up one directory level.',
  color: 'Changes the console foreground and background colors. Usage: "color [attr]" where attr is the color hex.',
  cls: "Clears the console screen of all previously entered commands and outputs.",
  help: 'Displays help information for available commands. Usage: "help" to list all commands.',
  exit: "Closes the command line interface.",
  about: "Displays information about the portfolio owner.",
  projects: "Lists all the projects in the portfolio.",
  contact: "Provides contact information.",
  skills: "Lists the skills and technologies the owner is proficient in.",
  time: "Displays the current system time.",
  date: "Displays the current system date.",
  resume: "Displays the resume (curriculum vitae) of the portfolio owner.",
  dir: "Displays the current directory and its content.",
  ver: 'Displays the "commandfolio" version number.',
  echo: 'Displays messages. Usage: "echo [message]" where message could be any text.',
  open: 'It opens the specified website. Usage: "open [url]" where url could be any valid URL like "google.com".',
};
